/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_APPWRITE_ENDPOINT: string
  readonly VITE_APPWRITE_PROJECT_ID: string
  readonly VITE_APPWRITE_DATABASE_ID: string
  readonly VITE_APPWRITE_PARENT_USERS_COLLECTION_ID: string
  readonly VITE_APPWRITE_YOUTH_PLAYERS_COLLECTION_ID: string
  readonly VITE_APPWRITE_COLLEGIATE_PLAYERS_COLLECTION_ID: string
  readonly VITE_APPWRITE_PROFESSIONAL_PLAYERS_COLLECTION_ID: string
  readonly VITE_APPWRITE_COACHES_COLLECTION_ID: string
  readonly VITE_APPWRITE_TEAM_TRAINING_COLLECTION_ID: string
  readonly VITE_APPWRITE_SIGNUPS_COLLECTION_ID: string
  readonly VITE_APPWRITE_CHECKINS_COLLECTION_ID: string
  readonly VITE_APPWRITE_COACH_SIGNUPS_COLLECTION_ID: string
  readonly VITE_APPWRITE_COACH_CHECKINS_COLLECTION_ID: string
  readonly VITE_APPWRITE_MESSAGES_COLLECTION_ID: string
  readonly VITE_APPWRITE_BILLS_COLLECTION_ID: string
  readonly VITE_APPWRITE_BILL_ITEMS_COLLECTION_ID: string
  readonly VITE_APPWRITE_PAYMENTS_COLLECTION_ID: string
  readonly VITE_APPWRITE_FAMILY_RELATIONSHIPS_COLLECTION_ID: string
  readonly VITE_APPWRITE_FAMILY_INVITATIONS_COLLECTION_ID: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
